services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - net_admin # required to modify network interfaces
    restart: on-failure:5
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /dev/net:/dev/net:z # tun device
    ports:
      - 8080:8080 #qbittorrent frontend port hopefully
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: on-failure:5
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/qBittorrent:/config # config files

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped


  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: on-failure:5
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
#       - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
# 
      - ${ROOT}/config/jackett:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: on-failure:5
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/media/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
# 
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: on-failure:5
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/media/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
# 
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    cap_add:
      - net_admin      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    network_mode: host
    volumes:
      - ${ROOT}/media/tv:/data/tvshows
      - ${ROOT}/config/jellyfin/library:/config
      - ${ROOT}/media/movies:/data/movies
    # ports:
      # - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: on-failure:5
# 
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: on-failure:5
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${ROOT}/media/movies:/movies # movies folder
      - ${ROOT}/media/tv:/tv # tv shows folder
      
  mylar3:
    container_name: mylar3
    image: linuxserver/mylar3:latest
    restart: on-failure:5
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/mylar3:/config
      - ${ROOT}/downloads:/downloads
      - ${ROOT}/media/comics:/comics

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    # network_mode: host
    environment:
      - TZ=${TZ}
      # - PUID=${PUID}
      # - PGID=${PGID}
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    ports:
      - 7575:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${ROOT}/config/homarr/appdata:/appdata
    restart: on-failure:5

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
      # - PORT=8083
    ports:
      - 8083:8080
    restart: on-failure:5

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${ROOT}/config/jellyseerr:/app/config
    restart: on-failure:5

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    
